/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marvellogram;

/**
 *
 * @author User
 */
public class calcuframe extends javax.swing.JFrame {

    /**
     * Creates new form calcuframe
     */
    public calcuframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstnl = new javax.swing.JLabel();
        secnl = new javax.swing.JLabel();
        firstn = new javax.swing.JTextField();
        sumb = new javax.swing.JButton();
        secn = new javax.swing.JTextField();
        reslt = new javax.swing.JTextField();
        sub = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        square = new javax.swing.JButton();
        cube = new javax.swing.JButton();
        sumulti = new javax.swing.JButton();
        productmulti = new javax.swing.JButton();
        capimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        firstnl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        firstnl.setForeground(new java.awt.Color(255, 255, 255));
        firstnl.setText("First Number :");
        jPanel1.add(firstnl);
        firstnl.setBounds(10, 60, 180, 40);

        secnl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        secnl.setForeground(new java.awt.Color(255, 255, 255));
        secnl.setText("Second Number :");
        jPanel1.add(secnl);
        secnl.setBounds(480, 50, 210, 50);

        firstn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        firstn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnActionPerformed(evt);
            }
        });
        firstn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstnKeyPressed(evt);
            }
        });
        jPanel1.add(firstn);
        firstn.setBounds(20, 110, 110, 40);

        sumb.setBackground(new java.awt.Color(0, 102, 153));
        sumb.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        sumb.setText("+");
        sumb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumbActionPerformed(evt);
            }
        });
        jPanel1.add(sumb);
        sumb.setBounds(20, 200, 80, 40);

        secn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jPanel1.add(secn);
        secn.setBounds(560, 110, 110, 40);

        reslt.setFont(new java.awt.Font("Tahoma", 3, 21)); // NOI18N
        jPanel1.add(reslt);
        reslt.setBounds(300, 280, 90, 40);

        sub.setBackground(new java.awt.Color(0, 102, 153));
        sub.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        sub.setText("-");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        jPanel1.add(sub);
        sub.setBounds(590, 190, 80, 40);

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 273, 80, 40);

        jButton2.setBackground(new java.awt.Color(0, 102, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("/");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(590, 260, 80, 40);

        square.setBackground(new java.awt.Color(0, 102, 153));
        square.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        square.setText("SQUARE");
        square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareActionPerformed(evt);
            }
        });
        jPanel1.add(square);
        square.setBounds(20, 420, 110, 40);

        cube.setBackground(new java.awt.Color(0, 102, 153));
        cube.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cube.setText("CUBE");
        cube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeActionPerformed(evt);
            }
        });
        jPanel1.add(cube);
        cube.setBounds(570, 413, 110, 40);

        sumulti.setBackground(new java.awt.Color(0, 102, 153));
        sumulti.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sumulti.setText("Sum of multiple numbers");
        sumulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumultiActionPerformed(evt);
            }
        });
        jPanel1.add(sumulti);
        sumulti.setBounds(10, 500, 210, 30);

        productmulti.setBackground(new java.awt.Color(0, 102, 153));
        productmulti.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productmulti.setText("Product of multiple no.");
        productmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productmultiActionPerformed(evt);
            }
        });
        jPanel1.add(productmulti);
        productmulti.setBounds(460, 493, 230, 30);

        capimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marvellogram/cb671ed097bf3f133ecc2c8c272c95ee.jpg"))); // NOI18N
        jPanel1.add(capimg);
        capimg.setBounds(0, 0, 702, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnActionPerformed

    private void sumbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumbActionPerformed
        // TODO add your handling code here:
        String s = firstn.getText();
        String sn = secn.getText();
        double a = Double.parseDouble(s);
        double b = Double.parseDouble(sn);
        double c = a+b;
        reslt.setText(Double.toString(c));
        
        
    }//GEN-LAST:event_sumbActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
        
        String s = firstn.getText();
        String sn = secn.getText();
        double a = Double.parseDouble(s);
        double b = Double.parseDouble(sn);
        double c = a-b;
        reslt.setText(Double.toString(c));

    }//GEN-LAST:event_subActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
                String s = firstn.getText();
        String sn = secn.getText();
        double a = Double.parseDouble(s);
        double b = Double.parseDouble(sn);
        double c = a*b;
        reslt.setText(Double.toString(c));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                String s = firstn.getText();
        String sn = secn.getText();
        double a = Double.parseDouble(s);
        double b = Double.parseDouble(sn);
        double c = a/b;
        reslt.setText(Double.toString(c));

    }//GEN-LAST:event_jButton2ActionPerformed

    private void squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareActionPerformed
        // TODO add your handling code here:
      new  Square().setVisible(true);
      this.setVisible(false);
        
    }//GEN-LAST:event_squareActionPerformed

    private void cubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeActionPerformed
        // TODO add your handling code here:
        new Cube().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cubeActionPerformed

    private void sumultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumultiActionPerformed
        // TODO add your handling code here:
        new Sumul().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sumultiActionPerformed

    private void productmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productmultiActionPerformed
        // TODO add your handling code here:
        new Promul().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_productmultiActionPerformed

    private void firstnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if(key == 10)
        {
            secn.requestFocus();
        }
    }//GEN-LAST:event_firstnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcuframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcuframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcuframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcuframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcuframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel capimg;
    private javax.swing.JButton cube;
    private javax.swing.JTextField firstn;
    private javax.swing.JLabel firstnl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton productmulti;
    private javax.swing.JTextField reslt;
    private javax.swing.JTextField secn;
    private javax.swing.JLabel secnl;
    private javax.swing.JButton square;
    private javax.swing.JButton sub;
    private javax.swing.JButton sumb;
    private javax.swing.JButton sumulti;
    // End of variables declaration//GEN-END:variables
}
