/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marvellogram;

/**
 *
 * @author User
 */
public class Cube extends javax.swing.JFrame {

    /**
     * Creates new form Cube
     */
    public Cube() {
        initComponents();
        cubrslt.setText("Cube");
        cubrslt.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cubnum = new javax.swing.JTextField();
        cubrslt = new javax.swing.JTextField();
        cubent = new javax.swing.JButton();
        back = new javax.swing.JButton();
        home = new javax.swing.JButton();
        bacpic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(509, 460));

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Number :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 90, 110, 30);

        cubnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubnumActionPerformed(evt);
            }
        });
        jPanel1.add(cubnum);
        cubnum.setBounds(210, 90, 180, 30);
        jPanel1.add(cubrslt);
        cubrslt.setBounds(210, 210, 180, 30);

        cubent.setBackground(new java.awt.Color(255, 0, 153));
        cubent.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        cubent.setText("Enter");
        cubent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubentActionPerformed(evt);
            }
        });
        jPanel1.add(cubent);
        cubent.setBounds(40, 210, 100, 30);

        back.setBackground(new java.awt.Color(0, 102, 153));
        back.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(310, 350, 90, 30);

        home.setBackground(new java.awt.Color(255, 0, 153));
        home.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home);
        home.setBounds(40, 350, 100, 30);

        bacpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marvellogram/sqrpic.jpg"))); // NOI18N
        jPanel1.add(bacpic);
        bacpic.setBounds(0, 0, 510, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new calcuframe().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        new calcuframe().setVisible(false);
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void cubentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubentActionPerformed
        // TODO add your handling code here:
        String s = cubnum.getText();
        double d = Integer.parseInt(s);
        cubrslt.setEnabled(true);
        cubrslt.setText(Double.toString(d*d*d));
    }//GEN-LAST:event_cubentActionPerformed

    private void cubnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubnumActionPerformed
        // TODO add your handling code here:
           String s = cubnum.getText();
        double d = Integer.parseInt(s);
        cubrslt.setEnabled(true);
        cubrslt.setText(Double.toString(d*d*d));
    }//GEN-LAST:event_cubnumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cube.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cube.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cube.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cube.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cube().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bacpic;
    private javax.swing.JButton cubent;
    private javax.swing.JTextField cubnum;
    private javax.swing.JTextField cubrslt;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
