/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marvellogram;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ProDiog extends javax.swing.JFrame {

    /**
     * Creates new form ProDiog
     */
     private int n,j=0,i=0,sume=0,k=1,l=1,flag=1,fl=1;
    private int x[][] = new int[100][100];
    public ProDiog() {
        initComponents();
              num.setText("No.");
        num.setEnabled(false);
          rslt.setText("\n\nProduct  Of  Diagonals.");
        rslt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        colm = new javax.swing.JTextField();
        row = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rslt = new javax.swing.JTextArea();
        bakpic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lemon", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" X");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 40, 40, 40);

        jLabel2.setFont(new java.awt.Font("Lemon", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Number :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 120, 200, 40);

        jLabel3.setFont(new java.awt.Font("Lemon", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order Of Matrix :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 40, 240, 40);

        num.setBackground(new java.awt.Color(0, 102, 153));
        num.setFont(new java.awt.Font("Lemon", 1, 22)); // NOI18N
        num.setForeground(new java.awt.Color(255, 255, 255));
        num.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numMouseEntered(evt);
            }
        });
        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });
        jPanel1.add(num);
        num.setBounds(210, 120, 180, 40);

        colm.setBackground(new java.awt.Color(0, 51, 51));
        colm.setFont(new java.awt.Font("Lemon", 1, 22)); // NOI18N
        colm.setForeground(new java.awt.Color(255, 255, 255));
        colm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colmMouseClicked(evt);
            }
        });
        jPanel1.add(colm);
        colm.setBounds(410, 40, 80, 40);

        row.setBackground(new java.awt.Color(0, 51, 51));
        row.setFont(new java.awt.Font("Lemon", 1, 22)); // NOI18N
        row.setForeground(new java.awt.Color(255, 255, 255));
        row.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rowMouseClicked(evt);
            }
        });
        row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rowActionPerformed(evt);
            }
        });
        row.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rowKeyPressed(evt);
            }
        });
        jPanel1.add(row);
        row.setBounds(260, 40, 90, 40);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Lemon", 1, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(390, 630, 120, 40);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Lemon", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 630, 110, 40);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Lemon", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Product");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(370, 190, 130, 40);

        rslt.setBackground(new java.awt.Color(0, 102, 153));
        rslt.setColumns(20);
        rslt.setFont(new java.awt.Font("Lemon", 1, 17)); // NOI18N
        rslt.setForeground(new java.awt.Color(255, 255, 255));
        rslt.setRows(5);
        jScrollPane1.setViewportView(rslt);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 440, 460, 150);

        bakpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marvellogram/ut2.jpg"))); // NOI18N
        jPanel1.add(bakpic);
        bakpic.setBounds(0, 0, 516, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
        // TODO add your handling code here:
          String s = row.getText();
        n = Integer.parseInt(s);
        String se = num.getText();
        x[i][j] = Integer.parseInt(se);
        if(j==n-1)
        {
            i++;
            j=0;
        }
        else
            j++;
        if(flag==n*n)
        {
            num.setText("Done");
            num.setEnabled(false);
        }
        else
            num.setText("");
        flag++;
    }//GEN-LAST:event_numActionPerformed

    private void numMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numMouseClicked
        // TODO add your handling code here:
         if(row.getText().equals(colm.getText()))
        {
        JOptionPane.showMessageDialog(this, "Press  'Enter'  After  Each  Number.");
        num.setText("");
        
        num.setEnabled(true);
        }
        else
            JOptionPane.showMessageDialog(this," Order of row and column must be same"); 
    }//GEN-LAST:event_numMouseClicked

    private void rowKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rowKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if(key==10)
        {
            colm.requestFocus();
        }
    }//GEN-LAST:event_rowKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String s = row.getText();
        n = Integer.parseInt(s);
        for(i=0;i<n;i++)
        {
            for(j=0;j<n;j++)
            {
               
            }
        }
        rslt.setEnabled(true);
        rslt.setText("");
       
for (i=0;i<n;i++)
{
for (j=0;j<n;j++)
{
if (i==j)
k=k*x[i][j];
if (i+j==n-1)
l=l*x[i][j];
}
}
rslt.setText("\nProduct of right diagonal element is : "+Integer.toString(k)+"\n\nProduct of left diagonal element is : "+Integer.toString(l));

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Matrix().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void numMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_numMouseEntered

    private void rowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rowActionPerformed

    private void rowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rowMouseClicked
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_rowMouseClicked

    private void colmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colmMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_colmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProDiog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProDiog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProDiog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProDiog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProDiog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakpic;
    private javax.swing.JTextField colm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField num;
    private javax.swing.JTextField row;
    private javax.swing.JTextArea rslt;
    // End of variables declaration//GEN-END:variables
}
