/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marvellogram;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class SumMat extends javax.swing.JFrame {

    /**
     * Creates new form SumMat
     */
    private int n,j=0,i=0,sume=0,k=0,l=0,flag=1,fl=1;
    private int x[][] = new int[100][100];
    private int y[][] = new int[100][100];
    private int z[][] = new int[100][100];
    
    
    public SumMat() {
        initComponents();
        num.setText("No.");
        num.setEnabled(false);
        num2.setText("No.");
        num2.setEnabled(false);
        rslt.setText("\n\nSum  Of  Both  The  Matrix");
        rslt.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        row = new javax.swing.JTextField();
        colm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        sum = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rslt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        num2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        bakpic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(493, 700));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lemon", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Order Of Matrix :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 20, 220, 40);

        jLabel3.setFont(new java.awt.Font("Lemon", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1st Matrix :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 180, 40);

        row.setBackground(new java.awt.Color(0, 51, 51));
        row.setFont(new java.awt.Font("Lemon", 1, 18)); // NOI18N
        row.setForeground(new java.awt.Color(255, 255, 255));
        row.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rowMouseClicked(evt);
            }
        });
        row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rowActionPerformed(evt);
            }
        });
        row.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rowKeyPressed(evt);
            }
        });
        jPanel1.add(row);
        row.setBounds(240, 20, 90, 40);

        colm.setBackground(new java.awt.Color(0, 51, 51));
        colm.setFont(new java.awt.Font("Lemon", 1, 18)); // NOI18N
        colm.setForeground(new java.awt.Color(255, 255, 255));
        colm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colmMouseClicked(evt);
            }
        });
        colm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colmActionPerformed(evt);
            }
        });
        jPanel1.add(colm);
        colm.setBounds(390, 20, 80, 40);

        jLabel4.setFont(new java.awt.Font("Lemon", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" X");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 20, 27, 30);

        num.setBackground(new java.awt.Color(0, 51, 51));
        num.setFont(new java.awt.Font("Lemon", 1, 24)); // NOI18N
        num.setForeground(new java.awt.Color(255, 255, 255));
        num.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numMouseClicked(evt);
            }
        });
        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });
        jPanel1.add(num);
        num.setBounds(210, 80, 130, 40);

        sum.setBackground(new java.awt.Color(0, 102, 102));
        sum.setFont(new java.awt.Font("Lemon", 1, 21)); // NOI18N
        sum.setForeground(new java.awt.Color(255, 255, 255));
        sum.setText("Sum");
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });
        jPanel1.add(sum);
        sum.setBounds(390, 180, 100, 37);

        rslt.setBackground(new java.awt.Color(0, 102, 153));
        rslt.setColumns(20);
        rslt.setFont(new java.awt.Font("Lemon", 1, 21)); // NOI18N
        rslt.setForeground(new java.awt.Color(255, 255, 255));
        rslt.setRows(5);
        jScrollPane1.setViewportView(rslt);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 440, 450, 170);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Lemon", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(383, 643, 100, 40);

        jLabel1.setFont(new java.awt.Font("Lemon", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("2nd Matrix :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 150, 190, 40);

        num2.setBackground(new java.awt.Color(0, 102, 153));
        num2.setFont(new java.awt.Font("Lemon", 1, 24)); // NOI18N
        num2.setForeground(new java.awt.Color(255, 255, 255));
        num2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num2MouseClicked(evt);
            }
        });
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        jPanel1.add(num2);
        num2.setBounds(210, 150, 130, 40);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Lemon", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 640, 100, 40);

        bakpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marvellogram/ut2.jpg"))); // NOI18N
        bakpic.setPreferredSize(new java.awt.Dimension(493, 700));
        jPanel1.add(bakpic);
        bakpic.setBounds(0, 0, 520, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void colmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colmActionPerformed

    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
        // TODO add your handling code here:
        String s = row.getText();
        n = Integer.parseInt(s);
        String se = num.getText();
        x[i][j] = Integer.parseInt(se);
        if(j==n-1)
        {
            i++;
            j=0;
        }
        else
            j++;
        if(flag==n*n)
        {
            num.setText("Done");
            num.setEnabled(false);
        }
        else
            num.setText("");
        flag++;
        
    }//GEN-LAST:event_numActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
        String s = colm.getText();
        n = Integer.parseInt(s);
        String se = num2.getText();
        y[k][l] = Integer.parseInt(se);
        if(l==n-1)
        {
            k++;
            l=0;
        }
        else
            l++;
        if(fl==n*n)
        {
            num2.setText("Done");
            num2.setEnabled(false);
        }
        else
            num2.setText("");
        fl++;
        
    }//GEN-LAST:event_num2ActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        // TODO add your handling code here:
        String s = row.getText();
        n = Integer.parseInt(s);
        for(i=0;i<n;i++)
        {
            for(j=0;j<n;j++)
            {
               z[i][j]=x[i][j]+y[i][j]; 
            }
        }
        rslt.setEnabled(true);
        rslt.setText("");
        for(i=0;i<n;i++)
        {
            for(j=0;j<n;j++)
            {
               if(j==n-1)
               rslt.setText(rslt.getText()+"       "+Integer.toString(z[i][j])+"\n");
               else
                   rslt.setText(rslt.getText()+"       "+Integer.toString(z[i][j]));
                   
               
            }
        }
        
    }//GEN-LAST:event_sumActionPerformed

    private void numMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numMouseClicked
        // TODO add your handling code here:
        
        if(row.getText().equals(colm.getText()))
        {
        JOptionPane.showMessageDialog(this, "Press  'Enter'  After  Each  Number.");
        num.setText("");
        
        num.setEnabled(true);
        }
        else
            JOptionPane.showMessageDialog(this," Order of row and column must be same"); 
    }//GEN-LAST:event_numMouseClicked

    private void num2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num2MouseClicked
        // TODO add your handling code here:
       
        num2.setText("");
        
        num2.setEnabled(true);
    }//GEN-LAST:event_num2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Matrix().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rowMouseClicked
        // TODO add your handling code here:
        num.setText("No.");num2.setText("No.");
    }//GEN-LAST:event_rowMouseClicked

    private void colmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colmMouseClicked
        // TODO add your handling code here:
         num.setText("No.");num2.setText("No.");
    }//GEN-LAST:event_colmMouseClicked

    private void rowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rowActionPerformed

    private void rowKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rowKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if(key == 10)
        {
            colm.requestFocus();
        }
    }//GEN-LAST:event_rowKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SumMat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SumMat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SumMat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SumMat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SumMat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakpic;
    private javax.swing.JTextField colm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField num;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField row;
    private javax.swing.JTextArea rslt;
    private javax.swing.JButton sum;
    // End of variables declaration//GEN-END:variables
}
