/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marvellogram;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Sumul extends javax.swing.JFrame {

    /**
     * Creates new form Sumul
     */
    private double sum;
    public Sumul() {
        initComponents();
        sum =0;
        mulrslt.setText("Sum Of All Numbers");
        mulrslt.setEnabled(false);
        mulnum.setText("Enter All Numbers");
        mulnum.setEnabled(false);
    }
       //static double sum;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mulent = new javax.swing.JButton();
        mulnum = new javax.swing.JTextField();
        mulrslt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bakpic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numbers :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 80, 140, 30);

        mulent.setBackground(new java.awt.Color(255, 0, 153));
        mulent.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        mulent.setText("Enter");
        mulent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulentActionPerformed(evt);
            }
        });
        jPanel1.add(mulent);
        mulent.setBounds(20, 210, 100, 30);

        mulnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mulnumMouseClicked(evt);
            }
        });
        mulnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulnumActionPerformed(evt);
            }
        });
        jPanel1.add(mulnum);
        mulnum.setBounds(250, 80, 170, 30);
        jPanel1.add(mulrslt);
        mulrslt.setBounds(250, 210, 170, 30);

        jButton2.setBackground(new java.awt.Color(255, 0, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 340, 100, 30);

        jButton3.setBackground(new java.awt.Color(0, 102, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(330, 340, 100, 30);

        bakpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marvellogram/sqrpic.jpg"))); // NOI18N
        jPanel1.add(bakpic);
        bakpic.setBounds(0, 0, 570, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new calcuframe().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        new Home().setVisible(true);
        this.setVisible(false);
        new calcuframe().setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mulentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulentActionPerformed
        // TODO add your handling code here:
        mulrslt.setEnabled(true);
        mulrslt.setText(Double.toString(sum));
        
    }//GEN-LAST:event_mulentActionPerformed

    private void mulnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulnumActionPerformed
        // TODO add your handling code here:
        String s= mulnum.getText();
        double d = Double.parseDouble(s);
        sum = sum+d;
        mulnum.setText("");
    }//GEN-LAST:event_mulnumActionPerformed

    private void mulnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulnumMouseClicked
        // TODO add your handling code here:
        mulnum.setEnabled(true);
        mulnum.setText("");
        JOptionPane.showMessageDialog(mulrslt, "Press  'Enter'  After  Each  Number.");
        sum=0;
        
        
    }//GEN-LAST:event_mulnumMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sumul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sumul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sumul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sumul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sumul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakpic;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mulent;
    private javax.swing.JTextField mulnum;
    private javax.swing.JTextField mulrslt;
    // End of variables declaration//GEN-END:variables
}
