/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marvellogram;

/**
 *
 * @author User
 */
public class Table extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    private int i;
    public Table() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabnum = new javax.swing.JTextField();
        table = new javax.swing.JButton();
        home = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tapp = new javax.swing.JTextArea();
        bakpic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Number :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 50, 160, 30);

        tabnum.setBackground(new java.awt.Color(0, 0, 102));
        tabnum.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tabnum.setForeground(new java.awt.Color(255, 255, 255));
        tabnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabnumMouseClicked(evt);
            }
        });
        tabnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabnumActionPerformed(evt);
            }
        });
        jPanel1.add(tabnum);
        tabnum.setBounds(240, 50, 130, 30);

        table.setBackground(new java.awt.Color(0, 0, 102));
        table.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setText("Table");
        table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableActionPerformed(evt);
            }
        });
        jPanel1.add(table);
        table.setBounds(30, 120, 110, 30);

        home.setBackground(new java.awt.Color(0, 0, 102));
        home.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home);
        home.setBounds(380, 320, 100, 30);

        reset.setBackground(new java.awt.Color(0, 0, 102));
        reset.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(380, 440, 100, 30);

        tapp.setBackground(new java.awt.Color(0, 0, 51));
        tapp.setColumns(20);
        tapp.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        tapp.setForeground(new java.awt.Color(255, 255, 255));
        tapp.setRows(5);
        jScrollPane1.setViewportView(tapp);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 300, 170, 390);

        bakpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marvellogram/tabl.jpg"))); // NOI18N
        jPanel1.add(bakpic);
        bakpic.setBounds(0, 0, 516, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableActionPerformed
        // TODO add your handling code here:
        String s = tabnum.getText();
        double d = Double.parseDouble(s);
        for(i=1;i<=10;i++)
        {
            tapp.setText(tapp.getText()+"\n\n"+ d+"  X  "+i+"  =  "+(d*i));
            
        }
    }//GEN-LAST:event_tableActionPerformed

    private void tabnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabnumActionPerformed
        // TODO add your handling code here:
         String s = tabnum.getText();
        double d = Double.parseDouble(s);
        for(i=1;i<=10;i++)
        {
            tapp.setText(tapp.getText()+"\n\n"+ d+"  X  "+i+"  =  "+(d*i));
            
        }

       
    }//GEN-LAST:event_tabnumActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        tabnum.setText("");
        tapp.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void tabnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabnumMouseClicked
        // TODO add your handling code here:
         tapp.setText("");
         tabnum.setText("");
    }//GEN-LAST:event_tabnumMouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         new Home().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakpic;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reset;
    private javax.swing.JButton table;
    private javax.swing.JTextField tabnum;
    private javax.swing.JTextArea tapp;
    // End of variables declaration//GEN-END:variables
}
